name: Publish

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'Action Run ID where the artifact is located'
        required: true
        type: number

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'publish'
  cancel-in-progress: true

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: sceneforge-docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "sceneforge/sceneforge"
          run-id: ${{ inputs.run-id }}
          path: ${{ github.workspace }}/dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/dist
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
