name: Publish

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID of the build workflow"
        required: true
        type: number

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download App Artifact
        uses: actions/download-artifact@v4
        with:
          name: sceneforge-docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "sceneforge/sceneforge"
          run-id: ${{ inputs.run_id }}
          path: ${{ github.workspace }}/dist
      
      - name: List files
        run: ls -la ${{ github.workspace }}/dist